# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11llm_service.proto\x12\x08theo.llm\"j\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12&\n\ntool_calls\x18\x03 \x03(\x0b\x32\x12.theo.llm.ToolCall\x12\x14\n\x0ctool_call_id\x18\x04 \x01(\t\"7\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\targuments\x18\x03 \x01(\t\"L\n\x0eToolDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x17\n\x0fparameters_json\x18\x03 \x01(\t\"\xb2\x01\n\x0fGenerateRequest\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.theo.llm.ChatMessage\x12\x15\n\rsystem_prompt\x18\x02 \x01(\t\x12\'\n\x05tools\x18\x03 \x03(\x0b\x32\x18.theo.llm.ToolDefinition\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05\x12\r\n\x05model\x18\x06 \x01(\t\"_\n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12&\n\ntool_calls\x18\x02 \x03(\x0b\x32\x12.theo.llm.ToolCall\x12\x15\n\rprocessing_ms\x18\x03 \x01(\x02\"v\n\x0bStreamEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x14\n\x0ctool_call_id\x18\x03 \x01(\t\x12\x11\n\ttool_name\x18\x04 \x01(\t\x12\x1c\n\x14tool_arguments_delta\x18\x05 \x01(\t2\x95\x01\n\nLLMService\x12\x41\n\x08Generate\x12\x19.theo.llm.GenerateRequest\x1a\x1a.theo.llm.GenerateResponse\x12\x44\n\x0eGenerateStream\x12\x19.theo.llm.GenerateRequest\x1a\x15.theo.llm.StreamEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=31
  _globals['_CHATMESSAGE']._serialized_end=137
  _globals['_TOOLCALL']._serialized_start=139
  _globals['_TOOLCALL']._serialized_end=194
  _globals['_TOOLDEFINITION']._serialized_start=196
  _globals['_TOOLDEFINITION']._serialized_end=272
  _globals['_GENERATEREQUEST']._serialized_start=275
  _globals['_GENERATEREQUEST']._serialized_end=453
  _globals['_GENERATERESPONSE']._serialized_start=455
  _globals['_GENERATERESPONSE']._serialized_end=550
  _globals['_STREAMEVENT']._serialized_start=552
  _globals['_STREAMEVENT']._serialized_end=670
  _globals['_LLMSERVICE']._serialized_start=673
  _globals['_LLMSERVICE']._serialized_end=822
# @@protoc_insertion_point(module_scope)
