# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import asp_common_pb2 as asp__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\x08theo.stt\x1a\x10\x61sp_common.proto\"u\n\nAudioChunk\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x15\n\raudio_payload\x18\x02 \x01(\x0c\x12&\n\x0c\x61udio_config\x18\x03 \x01(\x0b\x32\x10.asp.AudioConfig\x12\x15\n\rend_of_stream\x18\x04 \x01(\x08\"Y\n\x10TranscribeResult\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"a\n\x11TranscribeRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12&\n\x0c\x61udio_config\x18\x02 \x01(\x0b\x32\x10.asp.AudioConfig\x12\x10\n\x08language\x18\x03 \x01(\t\"M\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x15\n\rprocessing_ms\x18\x03 \x01(\x02\x32\x9f\x01\n\nSTTService\x12G\n\nTranscribe\x12\x1b.theo.stt.TranscribeRequest\x1a\x1c.theo.stt.TranscribeResponse\x12H\n\x10TranscribeStream\x12\x14.theo.stt.AudioChunk\x1a\x1a.theo.stt.TranscribeResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=49
  _globals['_AUDIOCHUNK']._serialized_end=166
  _globals['_TRANSCRIBERESULT']._serialized_start=168
  _globals['_TRANSCRIBERESULT']._serialized_end=257
  _globals['_TRANSCRIBEREQUEST']._serialized_start=259
  _globals['_TRANSCRIBEREQUEST']._serialized_end=356
  _globals['_TRANSCRIBERESPONSE']._serialized_start=358
  _globals['_TRANSCRIBERESPONSE']._serialized_end=435
  _globals['_STTSERVICE']._serialized_start=438
  _globals['_STTSERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
