# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stt_service_pb2 as stt__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stt_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTServiceStub(object):
    """=============================================================================
    STT Service - Speech-to-Text independente
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/theo.stt.STTService/Transcribe',
                request_serializer=stt__service__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=stt__service__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.TranscribeStream = channel.stream_stream(
                '/theo.stt.STTService/TranscribeStream',
                request_serializer=stt__service__pb2.AudioChunk.SerializeToString,
                response_deserializer=stt__service__pb2.TranscribeResult.FromString,
                _registered_method=True)


class STTServiceServicer(object):
    """=============================================================================
    STT Service - Speech-to-Text independente
    =============================================================================

    """

    def Transcribe(self, request, context):
        """Batch: envia audio completo, recebe transcricao
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeStream(self, request_iterator, context):
        """Streaming: envia chunks em tempo real, recebe parciais + final
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=stt__service__pb2.TranscribeRequest.FromString,
                    response_serializer=stt__service__pb2.TranscribeResponse.SerializeToString,
            ),
            'TranscribeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeStream,
                    request_deserializer=stt__service__pb2.AudioChunk.FromString,
                    response_serializer=stt__service__pb2.TranscribeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'theo.stt.STTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('theo.stt.STTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STTService(object):
    """=============================================================================
    STT Service - Speech-to-Text independente
    =============================================================================

    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theo.stt.STTService/Transcribe',
            stt__service__pb2.TranscribeRequest.SerializeToString,
            stt__service__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/theo.stt.STTService/TranscribeStream',
            stt__service__pb2.AudioChunk.SerializeToString,
            stt__service__pb2.TranscribeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
