# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import asp_common_pb2 as asp__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tts_service.proto\x12\x08theo.tts\x1a\x10\x61sp_common.proto\"n\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\'\n\routput_config\x18\x03 \x01(\x0b\x32\x10.asp.AudioConfig\x12\x10\n\x08voice_id\x18\x04 \x01(\t\"T\n\x12SynthesizeResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x02\x12\x15\n\rprocessing_ms\x18\x03 \x01(\x02\"F\n\nAudioChunk\x12\x15\n\raudio_payload\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x12\x10\n\x08sequence\x18\x03 \x01(\x05\x32\x9e\x01\n\nTTSService\x12G\n\nSynthesize\x12\x1b.theo.tts.SynthesizeRequest\x1a\x1c.theo.tts.SynthesizeResponse\x12G\n\x10SynthesizeStream\x12\x1b.theo.tts.SynthesizeRequest\x1a\x14.theo.tts.AudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=49
  _globals['_SYNTHESIZEREQUEST']._serialized_end=159
  _globals['_SYNTHESIZERESPONSE']._serialized_start=161
  _globals['_SYNTHESIZERESPONSE']._serialized_end=245
  _globals['_AUDIOCHUNK']._serialized_start=247
  _globals['_AUDIOCHUNK']._serialized_end=317
  _globals['_TTSSERVICE']._serialized_start=320
  _globals['_TTSSERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
