# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tts_service_pb2 as tts__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tts_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSServiceStub(object):
    """=============================================================================
    TTS Service - Text-to-Speech independente
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.unary_unary(
                '/theo.tts.TTSService/Synthesize',
                request_serializer=tts__service__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__service__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.SynthesizeStream = channel.unary_stream(
                '/theo.tts.TTSService/SynthesizeStream',
                request_serializer=tts__service__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=tts__service__pb2.AudioChunk.FromString,
                _registered_method=True)


class TTSServiceServicer(object):
    """=============================================================================
    TTS Service - Text-to-Speech independente
    =============================================================================

    """

    def Synthesize(self, request, context):
        """Batch: texto completo -> audio completo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeStream(self, request, context):
        """Streaming: texto -> stream de chunks de audio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=tts__service__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__service__pb2.SynthesizeResponse.SerializeToString,
            ),
            'SynthesizeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=tts__service__pb2.SynthesizeRequest.FromString,
                    response_serializer=tts__service__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'theo.tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('theo.tts.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService(object):
    """=============================================================================
    TTS Service - Text-to-Speech independente
    =============================================================================

    """

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/theo.tts.TTSService/Synthesize',
            tts__service__pb2.SynthesizeRequest.SerializeToString,
            tts__service__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/theo.tts.TTSService/SynthesizeStream',
            tts__service__pb2.SynthesizeRequest.SerializeToString,
            tts__service__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
